<a href="https://colab.research.google.com/github/FGalvao77/Machine-Learning/blob/main/Aula_5_2_Introdu%C3%A7%C3%A3o_ao_Tensor_Flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introdução ao Tensor Flow**

## **Preparando o conjunto de dados**

In [1]:
# importando as bibliotecas necessárias
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
# instanciando nosso conjunto de dados
fashion_mnist = keras.datasets.fashion_mnist

In [3]:
# carregando o conjunto de dados e separando os dados de treino e teste
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [4]:
# quantidade de imagens de treino
train_images.shape # um tensor de 3D - matriz de 60 mil elementos com dimensão de 28 por 28

(60000, 28, 28)

In [5]:
# quantidade de imagens de treino - rótulos
len(train_labels)

60000

In [6]:
# visualizando os rótulos das imagens de treino
np.unique(train_labels) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [7]:
# quantidade de imagens de teste
test_images.shape # um tensor de 3D - matriz de 10 mil elementos com dimensão de 28 por 28

(10000, 28, 28)

In [8]:
# quantidade de imagens de teste - rótulos
len(test_labels)

10000

In [9]:
# visualizando os rótulos das imagens de teste
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

**Podemos verificar que as nossas imagens de treino e teste é composto por uma matriz de 28 por 28. E cada elemento dessa matriz é exatamente um pixel com valores entre 0 e 255.**
  - onde 0 é a ausência de cor do pixel e 255 é a intensidade máxima de cor.


Em alguns modelos, tais como a regressão linear e as próprias redes neurais eles se benefeciam de atributos escalados. Esses modelos utilizam uma técnica de gradiente para otimização, ou seja uma derivada. Portanto quando esses valores está em uma escala pequena, entre 0 e 1 por exemplo, esses modelos são mais performáticos.

E como todos os nossos pixels está entre 0 e 255, então podemos dividir a nossa matriz por 255 e dessa maneira o pixel de maior intensidade que é 255 será igual a 1 e, o de menor intensidade que é 0 será logicamente 0. E os demais valores intermediários estará entre 0 e 1.

Aqui implicitamente utilizamos o `MinMaxScaler` sem chamar!

In [10]:
# vamos escalar as imagens de treino e teste
train_images = train_images / 255.0
test_images = test_images / 255.0

In [15]:
# visualizando a transformação
train_images[0] # perceba que, temos valores entre 0 e 1

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

## **Construção e avaliação do modelo TensorFlow**

In [16]:
# instanciando o modelo e seus parâmetros
model = keras.Sequential([
                          keras.layers.Flatten(input_shape=(28, 28)),
                          keras.layers.Dense(128, activation=tf.nn.relu),
                          keras.layers.Dense(10, activation=tf.nn.softmax)
])

# visualizando o modelo e seus parâmetros
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [18]:
# realizando a compilação do modelo e definindo os parâmetros
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [19]:
# treinando o modelo com as imagens de treino e os rótulos
model.fit(train_images, train_labels, epochs=5) # definindo 5 épocas de iteração para o treinamento

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4970 - accuracy: 0.8250
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3736 - accuracy: 0.8665
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3344 - accuracy: 0.8783
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3131 - accuracy: 0.8852
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2944 - accuracy: 0.8913


In [22]:
# avaliando o modelo e separando o valor de erro e o valor de acurácia
test_loss, test_acc = model.evaluate(test_images, test_labels)

# visualizando o teste de acurácia
print('Test accuracy: ', test_acc)

# visualizando o teste de erro
print('Test loss: ', test_loss)

313/313 [==============================] - 0s 1ms/step - loss: 0.3585 - accuracy: 0.8710
Test accuracy:  0.8709999918937683
Test loss:  0.35848140716552734


In [24]:
# utilizando a função ".predict()" que irar criar uma predição para cada imagem de teste
# e o resultado iremos instanciar na variável "predictions"
predictions = model.predict(test_images)

In [25]:
# visualizando a primeira predição
predictions[0]  # temos um array com 10 elementos com números em notação científica 

array([5.4737275e-06, 2.9802412e-09, 1.4978265e-07, 7.6548892e-09,
       3.3945472e-07, 2.2354526e-02, 7.2125972e-06, 4.5153249e-02,
       2.6089796e-05, 9.3245298e-01], dtype=float32)

In [26]:
# visualizando o elemento com predição de valor máximo
np.argmax(predictions[0])

9

In [27]:
# visualizando o rótulo da imagem de teste
test_labels[0]  # percebe que, o modelo acertou a primeira predição

9

In [31]:
# iremos instanciar a imagem de teste na variável "img"
# para posteriormente realizarmos uma avaliação individual
img = test_images[0]

# imprimindo a variável
print(img.shape)  # temos uma imagem de dimensão 28 por 28

(28, 28)


**Como nosso modelo espera um vetorde imagens e, aqui temos somente uma imagem sozinha.**
  - para isso, utlizaremos o numpy e a função `.expand_dims()` para expandir a dimensão das imagem e termos um vetor de uma única imagem.

In [32]:
# aplicando a função ".expand_dims()" do numpy
# ele irar expandir a dimensão da nossa imagem
# e iremos instanciar em uma nova variável "img"
img = (np.expand_dims(img, 0))

# visualizando a imagem expandida
print(img.shape)

(1, 28, 28)


In [33]:
# aplicando o modelo na imagem expandida
predictions_single = model.predict(img)

# visualizando a predição
print(predictions_single)

[[5.4737266e-06 2.9802407e-09 1.4978292e-07 7.6549176e-09 3.3945500e-07
  2.2354528e-02 7.2126109e-06 4.5153312e-02 2.6089841e-05 9.3245286e-01]]


In [35]:
# visualizando o elemento com predição de valor máximo
np.argmax(predictions_single[0])

9