<a href="https://colab.research.google.com/github/FGalvao77/Machine-Learning/blob/main/Oficina_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='tensor.png'>

<img src='parcs.png'>

In [1]:
# importando as bibliotecas necessárias
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [23]:
# carregando o conjunto de dados e instanciando na variável "fashion_mnist"
fashion_mnist = keras.datasets.fashion_mnist

# separando os dados de treino e teste 
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [24]:
# visualizando as imagens de treino
train_images.shape

(60000, 28, 28)

In [25]:
# visualizando a quantidade de rótulos das imagens de treino
len(train_labels)

60000

In [26]:
# visualizando os rótulos das imagens de treino
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [28]:
# quantidade de imagens de teste
test_images.shape # um tensor de 3D - matriz de 10 mil elementos com dimensão de 28 por 28

(10000, 28, 28)

In [29]:
# quantidade de imagens de treino - rótulos
len(test_labels)

10000

In [30]:
# visualizando os rótulos das imagens de teste
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [31]:
# vamos escalar as imagens de treino e teste
train_images = train_images / 255.0
test_images = test_images / 255.0

In [32]:
# instanciando o modelo e seus parâmetros
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(50, activation=tf.nn.relu),  # definindo a camada intermedária em 50 neurônios
    keras.layers.Dense(10, activation=tf.nn.softmax)
])

# visualizando o modelo e seus parâmetros
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 50)                39250     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                510       
Total params: 39,760
Trainable params: 39,760
Non-trainable params: 0
_________________________________________________________________


In [33]:
# realizando a compilação do modelo e definindo os parâmetros
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [34]:
# treinando o modelo com as imagens de treino e os rótulos
model.fit(train_images, train_labels, epochs=5) # definindo 5 épocas de iteração para o treinamento

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5235 - accuracy: 0.8177
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3970 - accuracy: 0.8605
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3623 - accuracy: 0.8700
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3378 - accuracy: 0.8776
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3223 - accuracy: 0.8840


In [35]:
# avaliando o modelo e separando o valor de erro e o valor de acurácia
test_loss, test_acc = model.evaluate(test_images, test_labels)

# visualizando o teste de acurácia
print('Test accuracy:', test_acc)

313/313 [==============================] - 0s 1ms/step - loss: 0.3822 - accuracy: 0.8637
Test accuracy: 0.8636999726295471


In [36]:
# utilizando a função ".predict()" que irar criar uma predição para cada imagem de teste
# e o resultado iremos instanciar na variável "predictions"
predictions = model.predict(test_images)

In [37]:
# visualizando a primeira predição
predictions[0]  # temos um array com 10 elementos com números em notação científica 

array([4.9426562e-06, 1.2948493e-07, 7.6635791e-09, 9.4017317e-08,
       4.1755459e-07, 2.4348223e-03, 1.0566383e-06, 2.2952277e-02,
       2.6961899e-05, 9.7457933e-01], dtype=float32)

In [38]:
# visualizando o elemento com predição de valor máximo
np.argmax(predictions[0])

9

In [39]:
# visualizando o rótulo da imagem de teste
test_labels[0]  # percebe que, o modelo acertou a primeira predição

9

In [40]:
# iremos instanciar a imagem de teste na variável "img"
# para posteriormente realizarmos uma avaliação individual
img = test_images[0]

# imprimindo a variável
print(img.shape)  # temos uma imagem de dimensão 28 por 28

(28, 28)


In [41]:
# aplicando a função ".expand_dims()" do numpy
# ele irar expandir a dimensão da nossa imagem
# e iremos instanciar em uma nova variável "img"
img = (np.expand_dims(img,0))

# visualizando a imagem expandida
print(img.shape)

(1, 28, 28)


In [42]:
# aplicando o modelo na imagem expandida
predictions_single = model.predict(img)

# visualizando a predição
print(predictions_single)

[[4.9426562e-06 1.2948493e-07 7.6635933e-09 9.4017501e-08 4.1755538e-07
  2.4348246e-03 1.0566383e-06 2.2952272e-02 2.6961898e-05 9.7457933e-01]]


In [43]:
# visualizando o elemento com predição de valor máximo
np.argmax(predictions_single[0])

9